### PR TITLE
TypeScript definition/examples

### PR DESCRIPTION
**Pull request by bradmartin**
- TypeScript definition file
- Sample for TS usage
- Added contributor

### CODE REVIEW

**Comment by msywensky** [comment]
Thanks Brad, looks good!

**Comment by bradmartin** [comment]
Mike, any chance you can publish this to npm?

**Comment by msywensky** [comment]
Will do, hopefully this evening.  Day job gets in the way.  :-)

**Comment by msywensky** [comment]
Done.

[cid:image002.png@01D15811.E0ED2020]

Mike Sywensky (michael.sywensky@pfizer.com<mailto:michael.sywensky@pfizer.com>)
Mobile Application Development, Business Technology
+1.484-268-3582 Mobile | +1.484-865-7019 Office

**Pull request merged**
